### ISSUE TITLE
DeprecationWarning: Tapable.plugin is deprecated

### ISSUE THREAD

**Issue by CristyTarantino** [davidwallacejackson/vue-cli-plugin-unit-karma#3]
With vue cli v 3.0.0-beta.10 I get this message when running test:unit

(node:30273) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead
ℹ ｢wdm｣: wait until bundle finished: noop

**Comment by davidwallacejackson** [comment]
I believe this is an issue with karma-webpack which has been fixed in the (yet to be officially released) webpack 4 version. Once that's out/stable, I can upgrade the dependency in this package and this problem should (hopefully) take care of itself.

https://github.com/webpack-contrib/karma-webpack/issues/320
